apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}-supervisor
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xinference-supervisor
    {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: xinference-supervisor
      {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      # Added for NVIDIA support
      runtimeClassName: {{ .Values.xinferenceSupervisor.runtimeClassName }}
      containers:
      - args: {{- toYaml .Values.xinferenceSupervisor.supervisor.args | nindent 8 }}
        command:
        - xinference-supervisor
        env:
        # Added NVIDIA environment variables
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: XINFERENCE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{- if .Values.config.persistence.enabled }}
        - name: XINFERENCE_HOME
          value: {{ .Values.config.persistence.mountPath }}
{{- end }}
{{- range $key, $value := .Values.config.extra_envs }}
        - name: {{ $key }}
          value: {{ $value }}
{{- end }}
{{- if .Values.config.xinference_image }}
        image: {{ .Values.config.xinference_image | quote }}
{{- else }}
        image: "xprobe/xinference:{{ .Chart.AppVersion }}"
{{- end }}
{{- if .Values.config.image_pull_policy }}
        imagePullPolicy: {{ .Values.config.image_pull_policy }}
{{- end }}
        name: supervisor
        ports: {{- toYaml .Values.xinferenceSupervisor.supervisor.ports | nindent 10 }}
        resources:
          {{- toYaml .Values.xinferenceSupervisor.supervisor.resources | nindent 10 }}
          # Added GPU limits
          limits:
            nvidia.com/gpu: 1
        # Added NVIDIA volume mounts
        volumeMounts:
        {{- if .Values.config.persistence.enabled }}
          - mountPath: {{ .Values.config.persistence.mountPath }}
            name: xinference-home
        {{- end }}
          - name: nvidia-driver
            mountPath: /usr/local/nvidia
      # Added NVIDIA volumes
      volumes:
      {{- if .Values.config.persistence.enabled }}
        - name: xinference-home
          persistentVolumeClaim:
            claimName: xinference-shared-volume-claim
      {{- end }}
        - name: nvidia-driver
          hostPath:
            path: /usr/local/nvidia
